<?php

namespace App\Exceptions;


use Illuminate\Database\Eloquent\ModelNotFoundException;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

trait ExceptionApiTrait
{
    public function apiException($request, $e){
        # code

        if ($e instanceof ModelNotFoundException) {
            return response()->json([
                'errors' => 'Model not found'
            ], Response::HTTP_NOT_FOUND);
        }

        if ($e instanceof NotFoundHttpException) {
            return response()->json([
                'errors' => 'Route not found'
            ], Response::HTTP_NOT_FOUND);
        }

        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }
}
